# Generated by Django 6.0.3 on 2026-05-21 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productvariant_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='additional_price',
        ),
    ]
